# Generated by Django 3.1.5 on 2021-02-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_board',
            fields=[
                ('board_number', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notice_board',
            },
        ),
        migrations.CreateModel(
            name='Progress_rate',
            fields=[
                ('rate_number', models.AutoField(primary_key=True, serialize=False)),
                ('progress_rate', models.FloatField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'progress_rate',
            },
        ),
        migrations.CreateModel(
            name='Study_book',
            fields=[
                ('studybook_number', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=300)),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Study_book',
            },
        ),
        migrations.CreateModel(
            name='Study_time',
            fields=[
                ('studytime_number', models.AutoField(primary_key=True, serialize=False)),
                ('study_time', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'study_time',
            },
        ),
        migrations.CreateModel(
            name='Studyroom',
            fields=[
                ('studyroom_number', models.AutoField(primary_key=True, serialize=False)),
                ('studyroom_classification', models.CharField(max_length=64)),
                ('studyroom_name', models.CharField(max_length=64)),
                ('studyroom_date', models.DateTimeField(auto_now_add=True)),
                ('leader_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to=settings.AUTH_USER_MODEL)),
                ('notice_board', models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Notice_board')),
                ('progress_rate', models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Progress_rate')),
                ('study_book', models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Study_book')),
                ('study_time', models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Study_time')),
            ],
            options={
                'verbose_name': 'Studyroom',
                'verbose_name_plural': 'Studyroom',
                'db_table': 'Studyroom',
            },
        ),
    ]
