# Generated by Django 3.1.5 on 2021-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_board',
            fields=[
                ('board_number', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'notice_board',
            },
        ),
        migrations.CreateModel(
            name='Progress_rate',
            fields=[
                ('rate_number', models.AutoField(primary_key=True, serialize=False)),
                ('progress_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'progress_rate',
            },
        ),
        migrations.CreateModel(
            name='Study_book',
            fields=[
                ('studybook_number', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Study_book',
            },
        ),
        migrations.CreateModel(
            name='Study_time',
            fields=[
                ('studytime_number', models.AutoField(primary_key=True, serialize=False)),
                ('study_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'study_time',
            },
        ),
        migrations.CreateModel(
            name='Studyroom',
            fields=[
                ('studyroom_number', models.AutoField(primary_key=True, serialize=False)),
                ('studyroom_classification', models.CharField(max_length=64)),
                ('studyroom_name', models.CharField(max_length=64)),
                ('studyroom_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Studyroom',
                'verbose_name_plural': 'Studyroom',
                'db_table': 'Studyroom',
            },
        ),
    ]
