# Generated by Django 3.1.7 on 2021-04-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('learning_time', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.calendar')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studyroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyroom_classification', models.CharField(max_length=64)),
                ('studyroom_name', models.CharField(max_length=64)),
                ('studyroom_date', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studyroom',
                'verbose_name_plural': 'Studyroom',
                'db_table': 'Studyroom',
            },
        ),
        migrations.CreateModel(
            name='Progress_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('studyroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.studyroom')),
            ],
        ),
        migrations.CreateModel(
            name='Progress_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalHour', models.IntegerField()),
                ('totalProgress', models.IntegerField()),
                ('studyroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.studyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='studyroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.studyroom'),
        ),
    ]
