# Generated by Django 3.1.5 on 2021-02-18 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='leader_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='notice_board',
            field=models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Notice_board'),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='progress_rate',
            field=models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Progress_rate'),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='study_book',
            field=models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Study_book'),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='study_time',
            field=models.ManyToManyField(blank=True, related_name='study_rooms', to='studyrooms.Study_time'),
        ),
        migrations.AddField(
            model_name='study_time',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study_book',
            name='writter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress_rate',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice_board',
            name='writter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
