# Generated by Django 3.1.5 on 2021-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_rate',
            name='totalHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress_rate',
            name='totalProgress',
            field=models.IntegerField(default=0),
        ),
    ]
