# Generated by Django 3.1.5 on 2021-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrooms', '0002_auto_20210218_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_time',
            name='study_time',
            field=models.IntegerField(),
        ),
    ]
