# Generated by Django 3.1.7 on 2021-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrooms', '0002_auto_20210405_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_task',
            name='taskNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
