# Generated by Django 3.1.7 on 2021-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_room',
            field=models.ManyToManyField(related_name='users', to='studyrooms.Studyroom'),
        ),
    ]
