# Generated by Django 3.1.5 on 2021-02-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrooms', '0001_initial'),
        ('users', '0002_my_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_page',
            name='make_study',
            field=models.ManyToManyField(related_name='make_study', to='studyrooms.Studyroom'),
        ),
        migrations.AddField(
            model_name='my_page',
            name='study_room',
            field=models.ManyToManyField(related_name='study_room', to='studyrooms.Studyroom'),
        ),
    ]
