# Generated by Django 3.1.5 on 2021-03-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210218_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='make_study',
        ),
    ]
