# Generated by Django 3.1.5 on 2021-03-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyrooms', '0002_auto_20210218_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Acceptance', models.CharField(choices=[('W', 'Waiting'), ('N', 'No'), ('Y', 'Yes')], default='W', max_length=1)),
                ('studyroomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='studyrooms.studyroom')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
