# Generated by Django 3.1.7 on 2021-04-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Acceptance',
        ),
    ]
