# Generated by Django 3.1.5 on 2021-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messagenumber', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
