# Generated by Django 3.1.5 on 2021-02-06 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_number', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('studyroom_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.studyroom')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
