# Generated by Django 3.1.5 on 2021-02-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studyrooms', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='studyroom_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyrooms.studyroom'),
        ),
    ]
